[Autologin]
Relogin=false
User=liveuser
Session=cosmic

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
CursorTheme=
Font=

[Users]
MaximumUid=60513
MinimumUid=1000
